# http://www.appveyor.com/docs/appveyor-yml

environment:
  matrix:
    - nodejs_version: 6

version: "{build}"
build: off
deploy: off

#branches:
#  except:
#    - gh-pages

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - ps: "npm test # PowerShell"
  - cmd: "npm test"
